### ISSUE TITLE
Why was cache_exceptions dropped?

### ISSUE THREAD

**Issue by FHTMitchell** [aio-libs/async-lru#593]
I can't find the PR but this [commit](https://github.com/aio-libs/async-lru/commit/23d95de1562b825d648b3264378c77b3f32e4514) dropped support for caching exceptions. The commit message says it makes no sense from a practical perspective. Why? If I know something is deterministic, it makes total sense for me to not want to recompute something I know is going to fail.

**Comment by Dreamsorcerer** [comment]
Yes, I'm just thinking of typical caching scenarios. It's certainly not an impossibility that you have a case where caching them makes sense, but the vast majority of the time it likely indicates a bug in someone's application rather than something they explicitly wanted to cache.

But, given that async functions are generally used for I/O, it's perhaps significantly more likely that an async function being cached is likely to throw a non-deterministic exception than a non-async function (within an asyncio application atleast). So, it probably makes less sense here than in functools (but, we'd probably still include it if they did, to keep it working as a drop-in replacement).
